lista_de_capas = [
    "demon slayer.png",
    "rick and morty.png",
    "membros akatsuki.png",
    "attack on titan.png",
    "borboletas.png",
    "cerejeira.png",
    "discord.png",
    "focal fossa.png",
    "gato.png",
    "jammy jellyfish.png",
    "levi.png",
    "montanhas.png",
    "naruto.png",
    "night.png",
    "paisagem.png",
    "sasuke.png",
    "castle.png",
    "dawn of dust.png",
    "gradient effect.png",
    "moon night.png",
    "hinata naruto.png",
    "stranger things.png",
    "tanjiro nezuko.png",
    "triangle neon.png",
    "ultra pink.png", 
    "logo akatsuki.png",
    "malevoly.png",
    "barbie.png",
    "obito.png"
]